services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: secreta
      MYSQL_DATABASE: smart-crop-manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: secreta
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/data
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: secreta
    restart: always
    ports:
      - 8091:80
    depends_on:
      - db

  backend:
    image: valomu81/smart-crop-manager-backend:latest
    container_name: smart-crop-backend
    restart: always
    ports:
      # - "8099:8099" # Puerto local original
      - "8099:8099" # Puerto estándar API VPS
    environment:
      PERFIL_ACTIVO: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/smart-crop-manager?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secreta
      FRONTEND_URL: http://192.168.9.234
    depends_on:
      - db

  # SERVICIO FRONTEND (Imágenes de Docker Hub)
  frontend:
    image: valomu81/smart-crop-manager-front:latest
    container_name: smart-crop-frontend
    restart: always
    ports:
      # - "80:80" # Puerto local original
      - "80:80" # Puerto web estándar VPS
    environment:
      # Si usas ngx-env o similar para parametrizar el frontend
      API_URL: http://192.168.9.234:8099/smart-crop-manager
    depends_on:
      - backend
volumes:
  dbdata: