spring.application.name=smart-crop-manager
server.port=8099

# CONFIGURACION BASE DE DATOS
spring.datasource.url=jdbc:mariadb://localhost:3307/smart-crop-manager?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=secreta

# HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACION JWT
jwt.secret=mi_clave_secreta_tfg_2026
jwt.issuer=smartcropmanager
jwt.access.expires=3600000
jwt.refresh.expires=86400000

spring.main.allow-circular-references=true